# Generated by Django 5.2.10 on 2026-01-22 15:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='Code de la commune', max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Commune',
                'verbose_name_plural': 'Communes',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeCulture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('MAIS', 'Maïs'), ('SOJA', 'Soja'), ('ANANAS', 'Ananas')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Type de Culture',
                'verbose_name_plural': 'Types de Cultures',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Arrondissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(help_text="Code de l'arrondissement", max_length=10)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrondissements', to='gestion.commune')),
            ],
            options={
                'verbose_name': 'Arrondissement',
                'verbose_name_plural': 'Arrondissements',
                'ordering': ['commune', 'nom'],
                'unique_together': {('nom', 'commune')},
            },
        ),
        migrations.CreateModel(
            name='Entrepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('capacite_max', models.DecimalField(decimal_places=2, help_text='Capacité maximale en kg', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('seuil_alerte', models.DecimalField(decimal_places=2, help_text="Seuil d'alerte de stock bas en kg", max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('arrondissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrepots', to='gestion.arrondissement')),
                ('gestionnaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrepots_geres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrepôt',
                'verbose_name_plural': 'Entrepôts',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Producteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=20)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('arrondissement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producteurs', to='gestion.arrondissement')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='producteur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producteur',
                'verbose_name_plural': 'Producteurs',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superficie', models.DecimalField(decimal_places=2, help_text='Superficie en hectares', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('nom', models.CharField(help_text='Nom ou identifiant de la parcelle', max_length=100)),
                ('arrondissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelles', to='gestion.arrondissement')),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelles', to='gestion.producteur')),
            ],
            options={
                'verbose_name': 'Parcelle',
                'verbose_name_plural': 'Parcelles',
                'ordering': ['producteur', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Recolte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, help_text='Quantité en kg', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_recolte', models.DateField()),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoltes', to='gestion.parcelle')),
                ('type_culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoltes', to='gestion.typeculture')),
            ],
            options={
                'verbose_name': 'Récolte',
                'verbose_name_plural': 'Récoltes',
                'ordering': ['-date_recolte'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, help_text='Quantité en stock en kg', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='gestion.entrepot')),
                ('type_culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='gestion.typeculture')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['entrepot', 'type_culture'],
                'unique_together': {('entrepot', 'type_culture')},
            },
        ),
    ]
